### ISSUE TITLE
What we need in slides

### ISSUE THREAD

**Issue by Winbobob** [SuperCh-SE-NCSU/Report-Slides#1]
First six original slides
- website + db +heroku
- send email (send grid)
- Python functions (obtain data from craglist and kbb)

**Comment by dragonfly90** [comment]
https://github.com/SuperCh-SE-NCSU/ProjectScraping/issues/17

function for model

**Comment by dragonfly90** [comment]
def craglistsearch(cmake,cmodel,cstartyear,cendyear,cminprice,cmaxprice,ctime)

**Comment by dragonfly90** [comment]
def craglistsearchKbb(carlist)
